service:
  version: 1.1.1
  url: https://geodata.nationaalgeoregister.nl/luchtfoto/rgb/wms?
  srs: EPSG:28992
  format: jpeg
  transparent: false
  layer: 2019_ortho25

bbox:
  west: 201763.0000
  south: 500353.0000
  east: 205310.0000
  north: 504609.0000

image:
  tempsize: 600
  size: 200
  resolution: 600
  directory: C:\Users\luukw\Desktop\nederland_500
  projection: EPSG:28992

analyzer:
  modelpath: model4

timeout: 300
bandscount: 3
tmpdirectory: ./tmp
threads: 12
