service:
  version: 1.1.1
  url: https://geodata.nationaalgeoregister.nl/luchtfoto/rgb/wms?
  srs: EPSG:28992
  format: jpeg
  transparent: false
  layer: 2019_ortho25

modes: 
  bbox:
    west: 201763.0000
    south: 500353.0000
    east: 205310.0000
    north: 504609.0000
  file: 
    location: ../index_nl_200.csv

mode: file
size: 200
resolution: 600
timeout: 300
projection: EPSG:28992
bandscount: 3
directory: D:\Luchtfotos\nederland_200
tmpdirectory: ../tmp
threads: 12
