service:
  version: 1.1.1
  url: https://geodata.nationaalgeoregister.nl/luchtfoto/rgb/wms?
  layer: 2019_ortho25
  transparent: false
  timeout: 300
  threads: 12
  
bbox:
  srs: EPSG:28992
  west: 201763
  south: 500353
  east: 205310
  north: 504609

image:
  tempsize: 600
  size: 200
  resolution: 600
  format: jpeg
  projection: EPSG:28992
  bandscount: 3
  
directory:
  images: C:\DIRECTORY\TO\STORE\IMAGES
  tmp: ./tmp
  model: C:\Program Files (x86)\AIDA\model4 